/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/** Represents data specific to builder in asynchronous state. */
export declare class AsyncState {}

/**
 * A prioritized configuration repository.
 *
 * It maintains a set of configuration sources, fetches values to populate those, and provides
 * them according to the source's priority.
 */
export declare class Config {
  /** Creates new [`ConfigBuilder`] instance */
  static builder(): ConfigBuilder
  get cache(): any
  getString(key: string): string
  getInt(key: string): number
  getFloat(key: string): number
  getBool(key: string): boolean
  getTable(key: string): any
  getArray(key: string): Array<any>
  get(key: string): any
  tryDeserialize(): any
  static tryFrom(from: any): Config
}

/** A configuration builder */
export declare class ConfigBuilder {
  constructor()
  setDefault(key: string, value: any): this
  setOverride(key: string, value: any): this
  setOverrideOption(key: string, value?: any | undefined | null): this
  addFile(filePath: string, format?: FileFormat | string | undefined | null): this
  addSource(source: File | Environment | Config): this
  build(): Config
  buildCloned(): Config
}

/** Represents data specific to builder in default state. */
export declare class DefaultState {}

export declare class Environment {
  static withPrefix(prefix: string): Environment
  static default(): Environment
  separator(separator: string): this
  ignoreEmpty(ignore: boolean): this
  keepPrefix(keep: boolean): this
}

export declare class File {
  static fromStr(s: string, format: FileFormat | string): File
  static new(name: string, format: FileFormat | string): File
  static withName(baseName: string): File
  format(format: FileFormat | string): this
  required(required: boolean): this
}

/** A configuration value. */
export declare class Value {
  static new(value: any, origin?: string): Value
  origin(): string | null
  tryDeserialize(): Value
  intoBool(): boolean
  intoInt(): number
  intoInt128(): number
  intoUint(): number
  intoUint128(): number
  intoFloat(): number
  intoString(): string
  intoArray(): Array<Value>
  intoTable(): Record<string, Value>
}

export declare const enum FileFormat {
  Toml = 'toml',
  Json = 'json',
  Yaml = 'yaml',
  Ini = 'ini',
  Ron = 'ron',
  Json5 = 'json5',
}
