/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare const __napiBindingTarget: "native" | "wasm32-wasi" | "wasm32-wasip1";

export declare class Config {
  static File: typeof File;
  static builder(): ConfigBuilder;
  get cache(): any;
  getString(key: string): string;
  getInt(key: string): number;
  getFloat(key: string): number;
  getBool(key: string): boolean;
  getTable(key: string): Record<string, any>;
  getArray(key: string): Array<any>;
  get(key: string): any;
  tryDeserialize(): any;
  static tryFrom(from: any): Config;
}

export declare class ConfigBuilder {
  constructor();
  setDefault(key: string, value: any): this;
  setOverride(key: string, value: any): this;
  setOverrideOption(key: string, value?: any | undefined | null): this;
  addSource(source: File | Environment | Config): this;
  build(): Config;
  buildCloned(): Config;
}

export declare class Environment {
  constructor();
  static withPrefix(prefix: string): Environment;
  static defaultEnv(): Environment;
  prefix(prefix: string): this;
  separator(separator: string): this;
  ignoreEmpty(ignoreEmpty: boolean): this;
  keepPrefix(keepPrefix: boolean): this;
}

export declare class File {
  static Format: typeof FileFormat;
  static withName(name: string): File;
  static fromStr(text: string, format: FileFormat | string): File;
  constructor(name: string, format?: FileFormat | string | undefined | null);
  static new(name: string, format?: FileFormat | string | undefined | null): File;
  format(format: FileFormat | string): this;
  required(required: boolean): this;
}

export declare class Value {
  static new(value: any, origin?: string): Value;
  origin(): string | null;
  tryDeserialize(): any;
  toJSON(): any;
  intoBool(): boolean;
  intoInt(): number;
  intoInt128(): number;
  intoUint(): number;
  intoUint128(): number;
  intoFloat(): number;
  intoString(): string;
  intoArray(): Array<Value>;
  intoTable(): Record<string, Value>;
}

export declare enum FileFormat {
  Ini = 0,
  Json = 1,
  Json5 = 2,
  Ron = 3,
  Toml = 4,
  Yaml = 5,
}
